# Introducción a Pandas

Primeramente, hay que verificar si están instalados los paquetes que necesitamos. El administrador de paquetes con el que se trabajan los módulos de Python es `pip`. Para ver los paquetes instalados se utiliza `pip list`.

Para instalar pandas, en caso de no tenerlo, se utiliza `pip install pandas`.

In [1]:
!pip list
# !pip install pandas
# !pip install <package_name>

Package                   Version
------------------------- --------------
anyio                     4.9.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 3.0.0
async-lru                 2.0.5
attrs                     25.3.0
babel                     2.17.0
beautifulsoup4            4.13.3
bleach                    6.2.0
certifi                   2025.1.31
cffi                      1.17.1
charset-normalizer        3.4.1
colorama                  0.4.6
comm                      0.2.2
contourpy                 1.3.1
cycler                    0.12.1
debugpy                   1.8.14
decorator                 5.2.1
defusedxml                0.7.1
executing                 2.2.0
fastjsonschema            2.21.1
fonttools                 4.57.0
fqdn                      1.5.1
h11                       0.14.0
httpcore                  1.0.8
httpx                     0.28.1
idna                      3.10
ipykernel                 6.29.5
ipython                   9.1.0
ipython_pygments_lexers   1.1.1
isoduration               20.11.0
jedi                      0.19.2
Jinja2                    3.1.6
json5                     0.12.0
jsonpointer               3.0.0
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
jupyter_client            8.6.3
jupyter_core              5.7.2
jupyter-events            0.12.0
jupyter-lsp               2.2.5
jupyter_server            2.15.0
jupyter_server_terminals  0.5.3
jupyterlab                4.4.0
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
kiwisolver                1.4.8
MarkupSafe                3.0.2
matplotlib                3.10.1
matplotlib-inline         0.1.7
mistune                   3.1.3
nbclient                  0.10.2
nbconvert                 7.16.6
nbformat                  5.10.4
nest-asyncio              1.6.0
notebook                  7.4.0
notebook_shim             0.2.4
numpy                     2.2.4
overrides                 7.7.0
packaging                 24.2
pandas                    2.2.3
pandocfilters             1.5.1
parso                     0.8.4
pillow                    11.2.1
pip                       25.0.1
platformdirs              4.3.7
prometheus_client         0.21.1
prompt_toolkit            3.0.50
psutil                    7.0.0
pure_eval                 0.2.3
pycparser                 2.22
Pygments                  2.19.1
pyparsing                 3.2.3
python-dateutil           2.9.0.post0
python-json-logger        3.3.0
pytz                      2025.2
pywin32                   310
pywinpty                  2.0.15
PyYAML                    6.0.2
pyzmq                     26.4.0
referencing               0.36.2
requests                  2.32.3
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.24.0
scipy                     1.15.3
Send2Trash                1.8.3
setuptools                78.1.0
six                       1.17.0
sniffio                   1.3.1
soupsieve                 2.6
stack-data                0.6.3
tabulate                  0.9.0
terminado                 0.18.1
tinycss2                  1.4.0
tornado                   6.4.2
traitlets                 5.14.3
types-python-dateutil     2.9.0.20241206
typing_extensions         4.13.2
tzdata                    2025.2
uri-template              1.3.0
urllib3                   2.4.0
wcwidth                   0.2.13
webcolors                 24.11.1
webencodings              0.5.1
websocket-client          1.8.0

## Sobre Pandas

Es una librería que permite trabajar con tablas o matrices de datos de una forma muy parecida a cómo se trabajaría una tabla de bases de datos o de excel, pero por medio de com

In [2]:
import pandas as pd

En Pandas, una serie es un arreglo unidimensional de datos. El tipo de dato de la serie depende de su contenido.

In [3]:
S = pd.Series([10, 20, 30, 40.1, 50])
print(S)

0    10.0
1    20.0
2    30.0
3    40.1
4    50.0
dtype: float64

Por otro lado, cuando se tienen arreglos de dos dimensiones, este se le llama _data frame_. Los data frames pueden ser trabajados como objetos (del tipo de JavaScript), para así crear una tabla con encabezados.

El contenido de cada lista tiene que tener la misma cantidad de datos para que el _data frame_ funcione.

In [4]:
datos = {
    'Nombre': ['Ana', 'Luis'],
    'Edad': [22, 35]
}

df = pd.DataFrame(datos)
print(df)

  Nombre  Edad
0    Ana    22
1   Luis    35

Además, los _data frames_ pueden exportarse como varios otros tipos de archivos. Es posible añadir más formatos para los archivos en cuestión; como por ejemplo el siguiente código exportará el data frame de arriba incluyendo una columna de índices.

In [5]:
df.to_csv("ejemplo.csv")

Así como se pueden exportar los data frames, pueden importarse desde varios archivos.

In [6]:
imported = pd.read_csv("ejemplo.csv")
print(imported)

   Unnamed: 0 Nombre  Edad
0           0    Ana    22
1           1   Luis    35

Ahora, a la hora de importar un data frame, queremos verificar que la importación a sido exitosa. Si el data frame es muy grande, es mejor verificar solo con las primeras o últimas filas; pero no todo el data frame.

In [7]:
# Imprime las primeras cinco filas del data frame
imported.head()

   Unnamed: 0 Nombre  Edad
0           0    Ana    22
1           1   Luis    35

In [8]:
# Imprime las últimas cinco filas del data frame
imported.tail()

   Unnamed: 0 Nombre  Edad
0           0    Ana    22
1           1   Luis    35

Otra función particularmente útil es aquella que nos da la información del data frame, del tipo de datos de las columnas y cantidad de datos.

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  2 non-null      object
 1   Edad    2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

También se tiene la función para realizar una descripción estadística del data frame por columna.

In [10]:
df.describe()

            Edad
count   2.000000
mean   28.500000
std     9.192388
min    22.000000
25%    25.250000
50%    28.500000
75%    31.750000
max    35.000000

También es posible trabajar con una cantidad de columnas que se desean, no tiene que ser todo el data frame.

In [11]:
filtered_df = df['Nombre']
print(filtered_df)

0     Ana
1    Luis
Name: Nombre, dtype: object

También es posible ver el tamaño del data frame, en las dos dimensiones. Esto es porque el data frame tiene un atributo, una tupla que empareja la cantidad de filas y columnas del data frame respectivamente.

In [12]:
print(df.shape)

(2, 2)

Entre otros atributos, están las columnas, que son tratadas como una estructura de datos. Por ejemplo:

In [13]:
columns = list(df.columns)
print(columns)

['Nombre', 'Edad']

Otra forma de verificar el tipo de datos que tienen cada columna del data frame es viendo al atributo `dtypes` del data frame.

In [14]:
print(df.dtypes)

Nombre    object
Edad       int64
dtype: object

Una opción que nos da Pandas es la capacidad de ver el valor de una celda en específico. Esto se hace con el atributo `iloc`.

In [15]:
print(int(df.iloc[0,1]))

22

Ahora, podemos verificar condicionales al data frame completo. Incluso, es posible obtener un data frame filtrado o discriminado respecto a la condicional dada.

In [16]:
df[df['Edad'] < 30]

  Nombre  Edad
0    Ana    22

Pueden usarse varios condicionales, unidos con operadores lógicos como `and`o `or`. Dentro de Pandas, `and = &` y `or = |`. Por ejemplo:

`df[(df['Scores'] < 21) & (df['Hours'] < 5)]`

Nótese que cada condición tiene que estar entre paréntesis.

Una forma para depurar datos, verificar si hay valores nulos, es por medio del método `isnull()`, el cual debería devolver un data frame con los valores `false` si los valores no son nulos, y `true`si lo son. Para mejor vista, se agrega el método `sum()` para ver cuántos valores hay nulos de cada columna.

In [17]:
print(df.isnull().sum())

Nombre    0
Edad      0
dtype: int64

Un método no recomendable, pero que existe, es `dropna()`, el cual borra todos los valores nulos

In [18]:
df.dropna()

  Nombre  Edad
0    Ana    22
1   Luis    35

Por medio de Pandas, se pueden agregar columnas, y se pueden alterar los valores de columnas.

In [19]:
df['Puntos'] = 5
df

  Nombre  Edad  Puntos
0    Ana    22       5
1   Luis    35       5

In [20]:
df['Puntos'] = 120
df

  Nombre  Edad  Puntos
0    Ana    22     120
1   Luis    35     120

Se pueden renombrar columnas...

In [21]:
df.rename(columns={'Puntos':'Puntaje'}, inplace=True)
df

  Nombre  Edad  Puntaje
0    Ana    22      120
1   Luis    35      120

Se pueden borrar columnas...

In [22]:
df.drop(columns={'Puntaje'}, inplace=True)
df

  Nombre  Edad
0    Ana    22
1   Luis    35